repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        language: system
        entry: cargo fmt --manifest-path source/rust/Cargo.toml -- --check
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        language: system
        entry: cargo clippy --manifest-path source/rust/Cargo.toml --all-targets -- -D warnings
        pass_filenames: false
